#ifndef _REALMODEPARM_H
#define _REALMODEPARM_H


#define REAL_MODE_DATA_BASE  0x2000
// #define PM32_EIP_OFF  (REAL_MODE_DATA_BASE + 0)
// #define PM32_ESP_OFF (REAL_MODE_DATA_BASE + 4)
#define E820MAP_NR  (REAL_MODE_DATA_BASE + 8)
#define E820MAP_ADR_ADR  (REAL_MODE_DATA_BASE + 12)

#endif